[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.5"
dependencies = [
    "ipykernel>=6.29.5",
    "pytest>=8.3.5",
    "pytest-cache>=1.0",
    "pytest-pylint>=0.21.0",
    "pytest-subtests>=0.14.1",
]
